[global]
   workgroup = WORKGROUP
   server string = Test SMB Server
   security = user
   map to guest = bad user

[public]
   path = /tmp/public
   browsable = yes
   guest ok = yes
   read only = no